### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by rlee1990** [msyshani/FitBit-Auth-for-iOS#3]
How can we have someone sign out of Fitbit?

**Comment by paulsumit1993** [comment]
I think invalidating/deleting the token should do it!

**Comment by rlee1990** [comment]
I tried to revoke it but its not working not sure if its how i am writing it

**Comment by paulsumit1993** [comment]
just delete/ignore it and initiate a new session, should work fine

**Comment by rlee1990** [comment]
That does not work i did that. The access is still there

**Comment by paulsumit1993** [comment]
Implicit or authorisation grant flow?

**Comment by rlee1990** [comment]
Implicit

**Comment by paulsumit1993** [comment]
that means your token will expire at the predefined time period, you cannot do anything about it.

**Comment by paulsumit1993** [comment]
please read the docs and post in Fitbit dev forum, that might help, Good luck!
